default: &default
  encoding: unicode
  adapter: postgis
  pool: 5
  timeout: 5000
  username: postgres
  database: pp_development

development:
  <<: *default
  host: "<%= ENV['POSTGRES_HOST'] || 'localhost' %>"
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"

test:
  <<: *default
  database: pp_test

production:
  <<: *default
  database: pp_production

staging:
  <<: *default
  database: pp_staging
