default: &default
  encoding: unicode
  adapter: postgis
  pool: 5
  timeout: 5000
  username: postgres

development:
  <<: *default
  host: "<%= ENV['POSTGRES_HOST'] || 'localhost' %>"
  username: "<%= ENV['POSTGRES_USER'] %>"
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"
  database: "<%= ENV['POSTGRES_DBNAME'] %>"

test:
  <<: *default
  database: pp_test

production:
  <<: *default
  database: pp_production

staging:
  <<: *default
  database: pp_staging
