service: protectedplanet-api

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: wcmc

builder:
  remote:
    arch: amd64
  dockerfile: Dockerfile.deploy

env:
  clear:
    APPSIGNAL_APP_NAME: protectedplanet-api
  secret:
    - RACK_SESSION_SECRET
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_DBNAME
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - CORS_ORIGINS
    - ADMIN_USERNAME
    - ADMIN_PASSWORD
    - MAILER_AUTHENTICATION
    - MAILER_ADDRESS
    - MAILER_DOMAIN
    - MAILER_USERNAME
    - MAILER_PASSWORD
    - MAILER_HOST
    - MAILER_PORT
    - APPSIGNAL_API_TOKEN